### ISSUE TITLE
create_local_taxonomy_db.py error

### ISSUE THREAD

**Issue by Sofie8** [kylebittinger/brocc#12]
Hello,

I am setting up the local database using create_local_taxonomy_db.py.
It created a database of around 5 Gb (5,541,363,712), but I also received an error (below), so not sure if it worked...
I have a Tb of space left, and the error says database full? I don't understand the error.
Can you suggest me a solution?

2019-04-23 06:05:11 (16.4 MB/s) - “/ddn1/vol1/site_scratch/leuven/314/vsc31426/db/brocc/tmpoykqldgv/taxdump.tar.gz” saved [48094496]

citations.dmp
delnodes.dmp
division.dmp
gencode.dmp
merged.dmp
names.dmp
nodes.dmp
gc.prt
readme.txt
Error: near line 14: database or disk is full
Error: near line 15: database or disk is full
Traceback (most recent call last):
  File "create_local_taxonomy_db.py", line 5, in <module>
    brocclib.taxonomy_db.main()
  File "/vsc-hard-mounts/leuven-data/314/vsc31426/miniconda3/envs/brocc/lib/python3.6/site-packages/brocclib/taxonomy_db.py", line 92, in main
    init_db(database_fp, download_dir, accessions, nodes)
  File "/vsc-hard-mounts/leuven-data/314/vsc31426/miniconda3/envs/brocc/lib/python3.6/site-packages/brocclib/taxonomy_db.py", line 187, in init_db
    subprocess.check_call(["sqlite3", db], stdin=f, cwd=temp_dir)
  File "/vsc-hard-mounts/leuven-data/314/vsc31426/miniconda3/envs/brocc/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sqlite3', '/ddn1/vol1/site_scratch/leuven/314/vsc31426/db/brocc/.brocc/taxonomy.db']' returned non-zero exit status 1.

Thank you!
Sofie

**Comment by scottdaniel** [comment]
I got a similar error when running creat_local_taxonomy_db.py

What seemed to fix it was installing brocc under python 2.7
